---
language: ruby
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.9" STRICT_VARIABLES="yes" FACTER_GEM_VERSION="2.4.6"
